### ISSUE TITLE
Cannot detect browsers

### ISSUE THREAD

**Issue by SoftwareRat** [nitin30kumar/edu-mail--auto-generator#1]
Hello,
your script cannot detect Firefox or Chrome on my Linux-based installation, even if i installed both browsers. Please fix it, i use Firefox ESR and ungoogled chromium

**Comment by nitinkumar30** [comment]
> Hello, your script cannot detect Firefox or Chrome on my Linux-based installation, even if i installed both browsers. Please fix it, i use Firefox ESR and ungoogled chromium

That maybe due to the wrong driver for your browser. Try with the drivers available for [Firefox](https://www.browserstack.com/guide/run-selenium-tests-using-firefox-driver) . For chromium, it's not supported for selenium now. Read [docs](https://www.selenium.dev/documentation/#supported-browsers-and-platforms) for more info.

Alternatively, you can run webdriver online for free [here](https://www.browserstack.com/users/sign_up?ref=guide-selenium-webdriver-tutorial-top&product=automate) .

Hope this is satisfying your question.
